# Generated by Django 4.0.3 on 2023-04-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='assignments.assignment'),
        ),
    ]
