# Generated by Django 4.0.3 on 2023-05-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0004_alter_mark_unique_together_mark_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
