version: '3.9'

services:
    db:
        image: postgres
        ports:
            - '5432:5432'

        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

        volumes:
            - ./backend/data/db:/var/lib/postgresql/data/

    django:
        build:
            context: ./backend/django
            dockerfile: Dockerfile

        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

        ports:
            - '8000:8000'

        volumes:
            - ./backend/django:/app/backend/django

        depends_on:
            - 'db'

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile

        ports:
            - '3000:3000'

        volumes:
            - ./frontend:/app/frontend

        depends_on:
            - 'django'
