# Generated by Django 4.1.7 on 2023-03-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
