# Generated by Django 4.0.3 on 2023-03-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_feed_alter_school_name'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
    ]
