# Generated by Django 4.0.3 on 2023-05-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_remove_course_feed_remove_course_files_folder_and_more'),
        ('subjects', '0003_alter_subject_description'),
        ('students', '0003_alter_student_user'),
        ('terms', '0003_alter_term_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='subjects.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='terms.year')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'year')},
            },
        ),
    ]
