# Generated by Django 4.0.3 on 2023-04-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_feed_alter_school_name'),
        ('students', '0003_alter_student_user'),
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('school', 'name')},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='students.student')),
            ],
            options={
                'unique_together': {('community', 'student')},
            },
        ),
        migrations.RemoveField(
            model_name='community',
            name='category',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='community',
            name='is_moderated',
        ),
        migrations.DeleteModel(
            name='CommunityCategory',
        ),
    ]
