# Generated by Django 4.0.3 on 2023-04-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at']},
        ),
    ]
