# Generated by Django 4.0.3 on 2023-03-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
        ('files', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='terms.cycle')),
                ('feed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.feed')),
                ('files_folder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='files.folder')),
            ],
        ),
    ]
