# Generated by Django 4.0.3 on 2023-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cycle',
        ),
    ]
