# Generated by Django 4.0.3 on 2023-04-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_alter_term_year'),
        ('groups', '0004_alter_group_unique_together_alter_group_grade'),
        ('courses', '0005_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='files_folder',
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='terms.year'),
        ),
    ]
