# Generated by Django 4.0.3 on 2023-03-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('posts', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.feed')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='grades.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
