# Generated by Django 4.1.7 on 2023-03-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="code",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="group",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_groups",
                to="schools.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("code", "school")},
        ),
        migrations.RemoveField(
            model_name="group",
            name="feed",
        ),
    ]
