# Generated by Django 4.1.7 on 2023-03-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        ("grades", "0005_alter_grade_school"),
        ("groups", "0003_alter_group_code_alter_group_school_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("school", "code")},
        ),
        migrations.AlterField(
            model_name="group",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students_groups",
                to="grades.grade",
            ),
        ),
    ]
