# Generated by Django 4.0.3 on 2023-03-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_feed_alter_school_name'),
        ('courses', '0004_remove_course_cycle'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='school',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='school_term_start_before_end',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='end_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='start_date',
            new_name='to_date',
        ),
        migrations.AddField(
            model_name='term',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='year',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='schools.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='terms.year'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('school', 'name')},
        ),
        migrations.RemoveField(
            model_name='term',
            name='cycle',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
