# Generated by Django 4.0.3 on 2023-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_alter_term_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_opened_to_marks',
            field=models.BooleanField(default=False),
        ),
    ]
