# Generated by Django 4.0.3 on 2023-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
