# Generated by Django 4.0.3 on 2023-04-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0006_alter_timebound_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timebound',
            options={'ordering': ['from_time', 'to_time']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['weekday', 'timebound']},
        ),
    ]
