# Generated by Django 4.0.3 on 2023-04-29 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-is_done', '-priority']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
