# Generated by Django 4.0.3 on 2023-04-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_done', '-priority']},
        ),
    ]
