# Generated by Django 4.0.3 on 2023-04-27 12:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_student_user'),
        ('courses', '0006_remove_course_feed_remove_course_files_folder_and_more'),
        ('groups', '0004_alter_group_unique_together_alter_group_grade'),
        ('schools', '0003_remove_school_feed_alter_school_name'),
        ('awards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='award',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issued_by_course_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issued_by_group_teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issued_by_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='award',
            name='points',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='award',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('school', 'name')},
        ),
        migrations.DeleteModel(
            name='AwardWinner',
        ),
        migrations.AddField(
            model_name='winner',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='awards.award'),
        ),
        migrations.AddField(
            model_name='winner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='courses.course'),
        ),
        migrations.AddField(
            model_name='winner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='groups.group'),
        ),
        migrations.AddField(
            model_name='winner',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.student'),
        ),
    ]
