# Generated by Django 4.0.3 on 2023-04-28 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0003_winner_award_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
