# Generated by Django 4.0.3 on 2023-04-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_alter_winner_course_alter_winner_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('-created_at',)},
        ),
    ]
