# Generated by Django 4.0.3 on 2023-04-28 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_feed_remove_course_files_folder_and_more'),
        ('groups', '0004_alter_group_unique_together_alter_group_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0007_alter_winner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
