# Generated by Django 4.1.7 on 2023-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_alter_grade_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
